# Exported from Render on 2025-01-12T15:36:24Z
services:
  - type: web
    name: mysite
    runtime: ruby
    repo: https://github.com/JoeAnsell/ror-blog
    plan: free
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        sync: false
      - key: DATABASE_URL
        sync: false
    region: oregon
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails server
version: "1"
