databases:
  - name: ror-blog-db
    databaseName: ror_blog
    user: ror_blog

services:
  - type: web
    name: ror-blog
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ror-blog-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
